#!/bin/bash -ex
#
# RightScript that installs a monitor script that returns a random value to collectd.
#
# Copyright RightScale, Inc. All rights reserved.
# All access and use subject to the RightScale Terms of Service available at
# http://www.rightscale.com/terms.php and, if applicable, other agreements
# such as a RightScale Master Subscription Agreement.
#

# Setup platform specific configuration
case "$RS_DISTRO" in
  ubuntu)
    config="/etc/collectd/collectd.conf"
    plugin_dir="/etc/collectd/plugins"
    if [ -d /etc/collectd/conf ]  # Then we appear to be on a variation of an Ubuntu deploy that uses a different plugin_dir
    then 
      plugin_dir="/etc/collectd/conf"
    fi
    lib_dir="/usr/lib/collectd"
    ;;
  centos)
    config="/etc/collectd.conf"
    plugin_dir="/etc/collectd.d"
    lib_dir="/usr/lib/collectd"
    ;;
  *)
    logger -s -t RightScale "RS_DISTRO of type $RS_DISTRO is not supported. This script is not supported on RightLink 10 servers. Exiting ...."
    exit 1
    ;;
esac

    
plugin_script_name="monitor_random"


# Install the script
echo -n "Installing collectd plugin ..."
mkdir -p $lib_dir/plugins
cp $ATTACH_DIR/$plugin_script_name $lib_dir/plugins/$plugin_script_name
chmod 775 $lib_dir/plugins/$plugin_script_name
echo "Done"
echo

# Create the collectd configuration
echo "Configuring collectd..."
cat << EOF > $plugin_dir/$plugin_script_name.conf
LoadPlugin exec
<Plugin exec>
  Exec "rightscale" "$lib_dir/plugins/$plugin_script_name" "$SERVER_UUID"
</Plugin>
EOF

echo "Done"
echo
  
# Restart the service
service collectd restart