#!/bin/bash -ex
#
# RightScript that installs a monitor script that returns a random value to collectd.
#
# Copyright RightScale, Inc. All rights reserved.
# All access and use subject to the RightScale Terms of Service available at
# http://www.rightscale.com/terms.php and, if applicable, other agreements
# such as a RightScale Master Subscription Agreement.
#

# Setup platform specific configuration
case "$RS_DISTRO" in
  ubuntu)
    config="/etc/collectd/collectd.conf"
    plugin_dir="/etc/collectd/plugins"
    lib_dir="/usr/lib/collectd"
    ;;
  centos)
    config="/etc/collectd.conf"
    plugin_dir="/etc/collectd.d"
    lib_dir="/usr/lib/collectd"
    ;;
  *)
    logger -s -t RightScale "Page checks not supported for platform: $RS_DISTRO. exiting..."
    exit 0
    ;;
esac

    
plugin_script_name="monitor_random"


# Install the script
echo -n "Installing collectd plugin ..."
mkdir -p $lib_dir/plugins
cp $ATTACH_DIR/$plugin_script_name $lib_dir/plugins/$plugin_script_name
chmod 775 $lib_dir/plugins/$plugin_script_name
echo "Done"
echo

# Create the collectd configuration
echo "Configuring collectd..."
cat << EOF > $plugin_dir/$plugin_script_name.conf
<Plugin exec>
  Exec "rightscale" "$lib_dir/plugins/$plugin_script_name" "$SERVER_UUID"
</Plugin>
EOF

# Ensure the exec plugin is enabled in the main collectd configuration file.
#exec_loaded=$(grep '^LoadPlugin exec' $config -c || true)

#if [ $exec_loaded = "0" ]; then
#  echo "The collectd exec plugin is not loaded, adding it to collectd.conf"
  # Make sure we add it BEFORE the include directive!
#  echo "LoadPlugin exec" >> $config
#fi
echo "Done"
echo
  
# Restart the service
service collectd restart
